#!/usr/bin/env bash
# Prints DNS information

printInfo() {
	dnsRecord=$(dig $1.$2 | grep -A1 'ANSWER SECTION:' | awk '/IN/ {print $4;}')
	ipAddress=$(dig $1.$2 | grep -A1 'ANSWER SECTION:' | awk '/IN/ {print $5;}')
	echo "The subdomain $1 is a $dnsRecord record and points to $ipAddress"
}

if [ $# -eq 1 ]; then
	printInfo "www" "$1"
	printInfo "lb-01" "$1"
	printInfo "web-01" "$1"
	printInfo "web-02" "$1"
elif [ $# -eq 2 ]; then
	printInfo "$2" "$1"
fi