#!/usr/bin/env bash
# Installs nginx

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
stringToReplace="^server {"
newString="server{\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s@${stringToReplace}@${newString}@" /etc/nginx/sites-available/default
sudo service nginx restart