#!/usr/bin/env bash
#Installs haproxy

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get install -y haproxy

sudo echo -e "\nfrontend http_front\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\nbackend http_back\n\tbalance roundrobin\n\tserver web-01 198.49.23.145:80 check\n\tserver web-02 142.250.68.174:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart